# Generated by Django 3.1.1 on 2020-09-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('rut_pasaporte', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido_m', models.CharField(max_length=15)),
                ('appelido_p', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'db_table': 'acompanante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id_chek_in', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_llegada', models.DateField()),
                ('estado_hbitacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'checkin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id_chek_out', models.AutoField(primary_key=True, serialize=False)),
                ('estado_entrega', models.CharField(max_length=20)),
                ('id_pago', models.IntegerField()),
            ],
            options={
                'db_table': 'checkout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido_m', models.CharField(max_length=15)),
                ('apellido_p', models.CharField(max_length=15)),
                ('vehiculo_patente', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'chofer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_pasaporte', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cel', models.BigIntegerField()),
                ('correo', models.CharField(max_length=30)),
                ('nacimineto', models.DateField()),
                ('nombre', models.CharField(max_length=15)),
                ('apellido_m', models.CharField(max_length=15)),
                ('apellido_p', models.CharField(max_length=15)),
                ('id_pago', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('desc_comuna', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('n_rol', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('n_banos', models.IntegerField()),
                ('n_habitaciones', models.IntegerField()),
                ('desc_habitacion', models.CharField(max_length=20)),
                ('precio_dia', models.BigIntegerField()),
                ('nombre_edificio', models.CharField(max_length=15)),
                ('n_departameto', models.IntegerField()),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.AutoField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('pellido_m', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=15)),
                ('valor', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('usuario', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mantencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('observaciones', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mantencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('id_multas', models.AutoField(primary_key=True, serialize=False)),
                ('n_mutas_cobras', models.IntegerField()),
                ('valor_multa', models.IntegerField()),
            ],
            options={
                'db_table': 'multas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('fecha_pago', models.DateField()),
                ('monto', models.BigIntegerField()),
                ('tipo_operacion', models.CharField(max_length=10)),
                ('descripcion_pago', models.CharField(max_length=10)),
                ('reserva_id_reserva', models.IntegerField()),
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('n_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_lelgada', models.DateField()),
                ('id_pago', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nom_servicio', models.CharField(max_length=10)),
                ('valor', models.IntegerField()),
                ('contrado', models.BooleanField()),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
                ('disponibilidad', models.IntegerField()),
                ('chofer_rut', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
    ]
